truffle-ai/dexto

configuration/README.md, configuration/mcp.json, src/client/mcp-client.ts
- Added support for windows "npx" defaults
- Updated configurations README.md
- Updated default mcp.json
=> Enhanced Windows support for npx

app/cli.ts, app/index.ts, configuration/saiki.yml, src/ai/llm/anthropic.ts, src/ai/llm/factory.ts, src/ai/llm/openai.ts, src/ai/llm/types.ts, src/ai/llm/vercel.ts, src/config/types.ts
This allows users to pass any system prompt they like to Saiki to customize the behaviour.
Currently placed systemPrompt as an LLMConfig option but we can move this if needed
Resolves #3
=> Add system prompt as a tunable parameter in saiki.yml under LLM config

src/ai/llm/messages/compression/middle-removal.ts, src/ai/llm/messages/compression/oldest-removal.ts, src/ai/llm/messages/compression/types.ts, src/ai/llm/messages/formatters/anthropic.ts, src/ai/llm/messages/formatters/openai.ts, src/ai/llm/messages/formatters/types.ts, src/ai/llm/messages/formatters/vercel.ts, src/ai/llm/messages/manager.ts, src/ai/llm/messages/types.ts, src/ai/llm/messages/utils.ts, src/ai/llm/services/anthropic.ts, src/ai/llm/services/openai.ts, src/ai/llm/services/vercel.ts, src/ai/llm/tokenizer/anthropic.ts, src/ai/llm/tokenizer/factory.ts, src/ai/llm/tokenizer/google.ts, src/ai/llm/tokenizer/openai.ts, src/ai/llm/tokenizer/types.ts, src/ai/llm/tokenizer/utils.ts
=> Fix formatting

.env.example, README.md, configuration/README.md, configuration/saiki.yml
All configs have been updated to use OpenAI by default
Docs have been updated for simpler setup and clearer usage instructions.
=> set configs to default openai; updated docs

README.md, app/index.ts, configuration/README.md, configuration/examples/email_slack.yml, configuration/examples/website_designer.yml, configuration/saiki.yml, src/ai/llm/services/README.md, src/ai/llm/services/factory.ts, src/client/mcp-client.ts, src/config/loader.ts, src/config/types.ts
Update environment variables to use standard $ instead of env prefix, update mcp-client to include a server specific timeout for tool calls
=> Improvements to environment variables and mcp server tool call timeouts

src/client/mcp-client.ts, src/config/loader.ts
forgot to set this.timeout in last PR
=> Fix mcp server timeout

app/cli/cli-subscriber.ts, app/cli/cli.ts, app/index.ts, app/web/server.ts, app/web/web-subscriber.ts, package.json
updated `package.json` to include `app` directory while formatting
then ran `npm run format`
=> Add app directory to format list and run npm run format

package-lock.json, package.json
this is to fix saiki cli installation issues
=> remove lint from prebuild

package-lock.json, package.json
more updates to fix saiki cli installation. unfortunately couldn't find a way to test this without pushing it
=> move devdependencies to dependencies

package-lock.json, package.json, src/ai/llm/services/vercel.ts
fix for #58 - we no longer have the check for `stepType`
=> Fix for tool emission in vercel llm service

app/web/client/index.html, app/web/client/script.js, app/web/client/style.css, app/web/server.ts, src/ai/llm/messages/formatters/anthropic.ts, src/ai/llm/messages/formatters/openai.ts, src/ai/llm/messages/formatters/types.ts, src/ai/llm/messages/formatters/vercel.ts, src/ai/llm/messages/manager.ts, src/ai/llm/messages/types.ts, src/ai/llm/messages/utils.ts, src/ai/llm/services/anthropic.ts, src/ai/llm/services/openai.ts, src/ai/llm/services/types.ts, src/ai/llm/services/vercel.ts, src/ai/llm/tokenizer/openai.ts, src/client/mcp-client.ts, src/utils/logger.ts
Updated the webui, Message Manager and vercel services for supporting image inputs.
Additionally, response emission in vercel service was moved to the onStepFunction to also capture thinking tokens generated along side toolCalls.
Vercel service was updated to add toolCalls and responses to message manager to maintain context throughout chat session.
Please review current implementation and suggest improvements. After review and edits, will also apply the changes to openai and anthropic services,
=> Add support for image parts/inputs

src/core/ai/llm/registry.ts
tested with:
saiki -m claude-4-opus-20250514 "hello"
saiki -m claude-4-sonnet-20250514 "hello"
both worked
logs:
```
[  9:17PM ]  [ karaj@MacBook-Pro:~/Projects/saiki/configuration(main✗) ]
$ saiki -m claude-4-opus-20250514 "hello"
21:17:59 INFO: Initializing Saiki with config: /Users/karaj/Projects/saiki/configuration/saiki.yml
21:17:59 INFO: New agent configuration loaded and validated.
21:17:59 INFO: Attempting to connect to new server 'filesystem'...
21:17:59 INFO: =======================================
21:17:59 INFO: MCP SERVER: npx -y @modelcontextprotocol/server-filesystem .
21:17:59 INFO: Environment:
21:17:59 INFO: =======================================
21:17:59 INFO: Connecting to MCP server: "filesystem" (npx -y @modelcontextprotocol/server-filesystem .)
21:17:59 INFO: …
```
=> Add claude 4 models and set sonnet 4 to default anthropic model

VERSIONING.md
=> doc updates

README.md, docs/docs/api/rest-api.md, docs/docs/getting-started/intro.md, docs/docs/getting-started/quick-start.md, docs/docs/user-guide/cli.md
broken links were causing docs build to fail
=> fix docs links and build

docs/docs/getting-started/intro.md, docs/docs/guides/cli.md, docs/docs/guides/configuring-saiki/llm/configuration.md, docs/docs/guides/configuring-saiki/llm/index.md, docs/docs/guides/configuring-saiki/llm/providers.md, docs/docs/tutorials/building-with-saiki/create-first-agent.md, docs/docs/tutorials/building-with-saiki/introduction.md, docs/docs/tutorials/building-with-saiki/whats-next.md, docs/docusaurus.config.ts
fixes broken links to fix the build
=> fix docs build

.github/workflows/claude.yml
need to merge to main to see if this works
=> testing claude code workflow

agents/examples/ollama.yml
note: gemma3n:e2b doesn't support tool calling from ollama
https://github.com/ollama/ollama/issues/9680
other models can be tried with ollama as well
=> Add new example file for ollama

agents/examples/README.md, agents/examples/linear-task-manager.yml
Added a comprehensive task management agent that integrates with Linear's official MCP server.
Key features:
- Uses npx mcp-remote to connect to https://mcp.linear.app/sse
- Issue management: create, update, search, and track Linear issues
- Project tracking and team collaboration capabilities
- Comment management and status updates
- Natural language interface for common task management workflows
tested linear mcp works and is able to call the auth callback
=> feat: add Linear task management agent example

docs/docs/tutorials/product-name-scout-agent.md
minor update to product name research agent docs
=> chore: update docs

README.md
- Bump type: Patch / Minor / Major (choose patch for all if unsure)
- Packages: ...
=> fix: remove header from README after logo addition
